# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_vec_R <- function(n, v) {
    invisible(.Call(`_exdebug_sort_vec_R`, n, v))
}

getEigenValues_R <- function(M) {
    .Call(`_exdebug_getEigenValues_R`, M)
}

getEigenValues_arma <- function(M) {
    .Call(`_exdebug_getEigenValues_arma`, M)
}

rcpparma_hello_world <- function() {
    .Call(`_exdebug_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_exdebug_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_exdebug_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_exdebug_rcpparma_bothproducts`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_exdebug_RcppExport_registerCCallable', PACKAGE = 'exdebug')
})
