// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/exdebug.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sort_vec_R
void sort_vec_R(int n, arma::vec v);
static SEXP _exdebug_sort_vec_R_try(SEXP nSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    sort_vec_R(n, v);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _exdebug_sort_vec_R(SEXP nSEXP, SEXP vSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_exdebug_sort_vec_R_try(nSEXP, vSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// getEigenValues_R
arma::vec getEigenValues_R(arma::mat M);
static SEXP _exdebug_getEigenValues_R_try(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigenValues_R(M));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _exdebug_getEigenValues_R(SEXP MSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_exdebug_getEigenValues_R_try(MSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// getEigenValues_arma
arma::vec getEigenValues_arma(arma::mat M);
static SEXP _exdebug_getEigenValues_arma_try(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigenValues_arma(M));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _exdebug_getEigenValues_arma(SEXP MSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_exdebug_getEigenValues_arma_try(MSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _exdebug_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _exdebug_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _exdebug_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _exdebug_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _exdebug_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("void(*sort_vec_R)(int,arma::vec)");
        signatures.insert("arma::vec(*getEigenValues_R)(arma::mat)");
        signatures.insert("arma::vec(*getEigenValues_arma)(arma::mat)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _exdebug_RcppExport_registerCCallable() { 
    R_RegisterCCallable("exdebug", "_exdebug_sort_vec_R", (DL_FUNC)_exdebug_sort_vec_R_try);
    R_RegisterCCallable("exdebug", "_exdebug_getEigenValues_R", (DL_FUNC)_exdebug_getEigenValues_R_try);
    R_RegisterCCallable("exdebug", "_exdebug_getEigenValues_arma", (DL_FUNC)_exdebug_getEigenValues_arma_try);
    R_RegisterCCallable("exdebug", "_exdebug_RcppExport_validate", (DL_FUNC)_exdebug_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_exdebug_sort_vec_R", (DL_FUNC) &_exdebug_sort_vec_R, 2},
    {"_exdebug_getEigenValues_R", (DL_FUNC) &_exdebug_getEigenValues_R, 1},
    {"_exdebug_getEigenValues_arma", (DL_FUNC) &_exdebug_getEigenValues_arma, 1},
    {"_exdebug_rcpparma_hello_world", (DL_FUNC) &_exdebug_rcpparma_hello_world, 0},
    {"_exdebug_rcpparma_outerproduct", (DL_FUNC) &_exdebug_rcpparma_outerproduct, 1},
    {"_exdebug_rcpparma_innerproduct", (DL_FUNC) &_exdebug_rcpparma_innerproduct, 1},
    {"_exdebug_rcpparma_bothproducts", (DL_FUNC) &_exdebug_rcpparma_bothproducts, 1},
    {"_exdebug_RcppExport_registerCCallable", (DL_FUNC) &_exdebug_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_exdebug(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
